version: '3.4'

services:
  gateway:
    ports:
      - "9000:80"
      - "9091:8080"

  client.app:
    expose:
      - "8080"

  auth.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - CommonSettings__RedisServiceName=redis:6379
    env_file:
      - ./env.files/token-options.env
    expose:
      - "80"

  middleware-jwt.val:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    env_file:
      - ./env.files/token-options.env
    expose:
      - "80"

  crypt.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    env_file:
      - ./env.files/rabbitmq-options.env
    expose:
      - "80"

  crypt.eventprocessor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:5000
    env_file:
      - ./env.files/rabbitmq-options.env
    expose:
      - "80"
      - "5000"

  redis:
    expose:
      - "6379"
    ports:
      - "8001:8001"
    volumes:
      - vol_redis_data:/data

  rabbitmq:
    env_file:
      - ./env.files/rabbitmq.env
    expose:
      - "5672"
    ports:
      - 15672:15672
    volumes:
      - vol_rabbitmq_data:/var/lib/rabbitmq
      - vol_rabbitmq_log:/var/log/rabbitmq

volumes:
  vol_rabbitmq_data:
  vol_rabbitmq_log:
  vol_redis_data:
