http:
  routers:
    auth.service:
      rule: "PathPrefix(`/api/auth`)"
      service: auth.service
    crypt.service:
      rule: "PathPrefix(`/api/crypt`)"
      service: crypt.service
      middlewares:
        - "middleware-jwt.val"
    web:
      rule: "PathPrefix(`/`)"
      service: web
  middlewares:
    middleware-jwt.val:
      forwardAuth:
        address: "http://middleware-jwt.val"
  services:
    crypt.service:
      loadBalancer:
        servers:
          - url: http://crypt.service
    web:
      loadBalancer:
        servers:
          - url: http://web