http:
  routers:
    crypt.service:
      rule: "PathPrefix(`/api/crypt`)"
      service: crypt.service
      middlewares:
        - "middleware-jwt.val"
    auth.service:
      rule: "PathPrefix(`/api/auth`)"
      service: auth.service
    client.app:
      rule: "PathPrefix(`/`)"
      service: client.app
    crypt.eventprocessor:
      rule: "PathPrefix(`/hubs/crypt`)"
      service: client.app
  middlewares:
    middleware-jwt.val:
      forwardAuth:
        address: "http://middleware-jwt.val"
  services:
    crypt.service:
      loadBalancer:
        servers:
          - url: http://crypt.service
    auth.service:
      loadBalancer:
        servers:
          - url: http://auth.service
    client.app:
      loadBalancer:
        servers:
          - url: http://client.app
    crypt.eventprocessor:
      loadBalancer:
        servers:
          - url: http://crypt.eventprocessor